config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get "/top10_articles", to: 'articles#showtop10'
  get "/favorites", to:'articles#favorites'
  get "/allarticles", to:'articles#allarticles'

resources :articles do
  resources :comments
end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments,dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
  length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments,dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # http_basic_authenticate_with name: "shreyash", password: "secret", except: [:index, :show]
  def new
    @article=Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end
  def show
    @article = Article.find(params[:id])
  end

  def showtop10
    @articles = Article.order(id: :desc).limit(10)
  end


  def favorites
    @articles= Article.where(checkbox: true)
  end

  def allarticles
    @articles= Article.all
  end

  def index
    @articles =current_user.articles
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text,:checkbox)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # http_basic_authenticate_with name: "shreyash", password: "secret", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body).merge(user_id: current_user.id)

end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user.email
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

   <p>
      <%= form.label(:checkbox, "Favorite") %>
      <%= form.check_box :checkbox %>
    </p>

  <p>
    <%= form.submit %>
  </p>


<% end %>

app/views/articles/allarticles.html.erb
<h1>All Articles </h1>
<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

<% @articles.each do |article | %>
    <tr>
    <td><%= article.id %></td>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>


<%= link_to 'Back', articles_path %>

app/views/articles/favorites.html.erb
<h1>Favorites Article </h1>
<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

<% @articles.each do |article | %>
    <tr>
    <td><%= article.id %></td>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>

  <% end %>
</table>

<%= link_to ' All articles', allarticles_path %>
<br>
<%= link_to ' Top 10 Articles', top10_articles_path %>
<br>
<%= link_to 'Favorites Article', favorites_path%> <br>
<%= link_to 'Index Page', welcome_index_path%>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>

app/views/articles/showtop10.html.erb
<h1>Top 10 Article </h1>
<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

<% @articles.each do |article | %>
    <tr>
    <td><%= article.id %></td>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.user.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<%if comment.user === current_user %>
  <p>
    <%= link_to 'Destroy Comment', [comment.article, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>
<p>
  <strong>Created at </strong>
  <%= comment.created_at %>
</p>
<p>
  <strong>Last Updated</strong>
  <%= comment.updated_at %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello</h1>
<%=+@user%>
<%= current_user.id%>
<%= link_to 'My Blog', controller: 'articles' %>
<li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
<h2>Show top 10 articles</h2>